###
PUT http://localhost:4000/author-api/delete
Content-Type: application/json

{
    "articleId": 123,
    "authorUsername":"vishnuvardhan"
}

###
GET http://localhost:4000/author-api/a

###
POST http://localhost:4000/author-api/register
Content-Type: application/json

{
    "authorUsername": "vishnuvardhan",
    "email": "vishnuvardhan@gmail.com",
    "password": "vishnu123"
}

###
POST http://localhost:4000/author-api/login
Content-Type: application/json

{
    "authorUsername": "vishnuvardhan",
    "password": "vishnu123"
}

###
POST http://localhost:4000/author-api/submit-article
Content-Type: application/json

{
    "articleId":"{{$timestamp}}",
    "title": "My Article",
    "content": "This is my article",
    "authorUsername": "vishnu",
    "status": "true",
    "likes":0,
    "comments":[],
    "modifiedDate":"{{$datetime iso8601}}",
    "createdDate":"{{$datetime iso8601}}"
}

###
PUT http://localhost:4000/author-api/edit-article/1730131767
Content-Type: application/json

{
    "content": "This is my new edited article",
    "authorUsername": "vishnu"
}